import { EmailOptions, IpOptions, Reference, UriOptions } from "joi";
export declare function Alphanum(): PropertyDecorator;
export declare function CreditCard(): PropertyDecorator;
export declare function Email(options?: EmailOptions): PropertyDecorator;
export declare function Guid(): PropertyDecorator;
export declare function Hex(): PropertyDecorator;
export declare function Hostname(): PropertyDecorator;
export declare function Ip(options?: IpOptions): PropertyDecorator;
export declare function IsoDate(): PropertyDecorator;
export declare function Length(limit: number | Reference, encoding?: string): PropertyDecorator;
export declare function Lowercase(): PropertyDecorator;
export declare function Max(limit: number | Reference, encoding?: string): PropertyDecorator;
export declare function Min(limit: number | Reference, encoding?: string): PropertyDecorator;
export declare function Regex(pattern: RegExp, name?: string): PropertyDecorator;
export declare const Pattern: typeof Regex;
export declare function Replace(pattern: RegExp, replacement: string): PropertyDecorator;
export declare function StringSchema(): PropertyDecorator;
export declare function Token(): PropertyDecorator;
export declare function Trim(): PropertyDecorator;
export declare function Uppercase(): PropertyDecorator;
export declare function Uri(options?: UriOptions): PropertyDecorator;
